import React, { Component } from 'react';
import { Notifications } from 'react-native-notifications';

class MyComponent extends Component {
  async componentDidMount() {
    try {
      await Notifications.requestPermissions();
      Notifications.registerRemoteNotifications();

      Notifications.events().registerNotificationReceivedForeground((notification, completion) => {
        console.log(`Notification received in foreground: ${notification.title} : ${notification.body}`);
        completion({ alert: false, sound: false, badge: false });
      });

      Notifications.events().registerNotificationOpened((notification, completion) => {
        console.log(`Notification opened: ${notification.payload}`);
        completion();
      });

      // Trigger local notification when the component is mounted
      Notifications.postLocalNotification({
        title: "Local notification",
        body: "This notification was generated by the app!",
      });
    } catch (error) {
      console.error("Error setting up notifications:", error);
    }
  }

  componentWillUnmount() {
    // Unregister the event listeners when the component is unmounted
    Notifications.events().unregisterNotificationReceivedForeground();
    Notifications.events().unregisterNotificationOpened();
  }

  render() {
    return (
    <></>
      // Your component JSX here
    );
  }
}

export default MyComponent;
